In [1]:
import torch

In [4]:
x = [ 2, 36, 80, 77, 77, 70, 68, 85,  1, 85, 73, 70,  1, 85, 70, 83, 78, 84,
         1, 74, 79,  1, 14, 23, 11, 85, 11, 11, 20,  1, 12,  1, 85, 11, 11, 19,
         1, 12,  1, 85, 11, 11, 19,  1, 14,  1, 23, 23, 11, 85,  1, 12,  1, 23,
        23, 11, 85,  1, 12,  1, 17, 11, 85, 11, 11, 19, 15,  3,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]

In [18]:
x = torch.Tensor(x).reshape(1,-1)
x = x.to(torch.int64)
x = torch.transpose(x, 0, 1)
x.shape

torch.Size([162, 1])

In [19]:
x

tensor([[ 2],
        [36],
        [80],
        [77],
        [77],
        [70],
        [68],
        [85],
        [ 1],
        [85],
        [73],
        [70],
        [ 1],
        [85],
        [70],
        [83],
        [78],
        [84],
        [ 1],
        [74],
        [79],
        [ 1],
        [14],
        [23],
        [11],
        [85],
        [11],
        [11],
        [20],
        [ 1],
        [12],
        [ 1],
        [85],
        [11],
        [11],
        [19],
        [ 1],
        [12],
        [ 1],
        [85],
        [11],
        [11],
        [19],
        [ 1],
        [14],
        [ 1],
        [23],
        [23],
        [11],
        [85],
        [ 1],
        [12],
        [ 1],
        [23],
        [23],
        [11],
        [85],
        [ 1],
        [12],
        [ 1],
        [17],
        [11],
        [85],
        [11],
        [11],
        [19],
        [15],
        [ 3],
        [ 0],
        [ 0],
        [ 0],
      

In [21]:
y = torch.nn.functional.one_hot(x, 95)

In [22]:
y

tensor([[[0, 0, 1,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[1, 0, 0,  ..., 0, 0, 0]],

        [[1, 0, 0,  ..., 0, 0, 0]],

        [[1, 0, 0,  ..., 0, 0, 0]]])

In [23]:
y.shape

torch.Size([162, 1, 95])

In [25]:
z = y.unsqueeze(0)

In [26]:
z

tensor([[[[0, 0, 1,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0]],

         ...,

         [[1, 0, 0,  ..., 0, 0, 0]],

         [[1, 0, 0,  ..., 0, 0, 0]],

         [[1, 0, 0,  ..., 0, 0, 0]]]])

In [27]:
z.shape

torch.Size([1, 162, 1, 95])